name: Notify on Update

on:
  push:
    paths:
      - '**.txt'

jobs:
  notify:
    runs-on: ubuntu-latest  # Specifica l'ambiente di esecuzione

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Assicurati di controllare il codice sorgente

    - name: Read email body from file
      id: read-body
      run: |
        body=$(cat body.txt)
        echo "::set-output name=body::$body"

    - name: Send Email Notification
      uses: dawidd6/action-send-mail@v3  # Utilizza l'azione per inviare email
      with:
        server_address: smtp.gmail.com # Modifica se utilizzi un altro server SMTP
        server_port: 465  # Usa 587 per TLS, 465 per SSL
        username: ${{ secrets.SMTP_USERNAME }}  # Indirizzo email dal segreto
        password: ${{ secrets.SMTP_PASSWORD }}  # Password dell'email dal segret
        subject: "IBiSco: Jobs eseguiti con successo!"
        body: ${{ steps.read-email-body.outputs.body }}  # Usa il contenuto letto dal file come corpo dell'email
        to: "dario.espo1995@gmail.com"  # Inserisci l'indirizzo email del destinatario
        from: ${{ secrets.SMTP_USERNAME }} # Utilizza lo stesso indirizzo email per 'from"
